---
abstract: 'A POE filter for HTTP based on HTTP::Parser '
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-HTTP-Parser
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  HTTP::Parser: 0.04
  HTTP::Status: 0
  POE: 1.003
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
