---
abstract: 'A HTTP POE filter for HTTP clients or servers'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
  Test::POE::Client::TCP: 0.1
  Test::POE::Server::TCP: 0.16
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-HTTP-Parser
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Filter::HTTP::Parser:
    file: lib/POE/Filter/HTTP/Parser.pm
    version: 1.02
requires:
  HTTP::Parser: 0.04
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Status: 0
  POE: 1.003
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-filter-http-parser/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-http-parser.git
version: 1.02
