---
abstract: 'A HTTP POE filter for HTTP clients or servers'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
  Test::POE::Client::TCP: 0.1
  Test::POE::Server::TCP: 0.16
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-HTTP-Parser
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  HTTP::Parser: 0.04
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Status: 0
  POE: 1.003
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
